import { useMemo, useState } from 'react';
import { Add, DeleteOutline } from '@mui/icons-material';
import { currency, lineTotals, quotationTotals } from '../utils/quotationCalculations';
import { validateQuotation } from '../utils/quotationValidation';
import { SearchablePicker } from './SearchablePicker';

const emptyItem = () => ({ id: `new-${Date.now()}-${Math.random()}`, productId: '', productName: '', description: '', quantity: 1, unitPrice: 0, discountType: 'percentage', discountRate: 0, discountAmount: 0, taxType: 'GST', taxRate: 18, hsnSac: '' });
export function newQuotation() { const date = new Date().toISOString().slice(0, 10); const until = new Date(); until.setDate(until.getDate() + 30); return { customerId: '', quotationDate: date, validUntil: until.toISOString().slice(0, 10), reference: '', items: [emptyItem()], invoiceDiscount: { type: 'percentage', value: 0 }, charges: [], notes: 'Thank you for your business.', termsAndConditions: 'Payment due within 30 days.' }; }
export function QuotationForm({ initial, customers, products, onSave, onCancel, readOnly = false }) {
  const [form, setForm] = useState(() => ({ ...newQuotation(), ...initial, customerId: initial?.customerId || initial?.customer?.id || '' })); const [errors, setErrors] = useState({}); const [discountAuthorized, setDiscountAuthorized] = useState(true);
  const selectedCustomer = customers.find(customer => customer.id === form.customerId); const totals = useMemo(() => quotationTotals(form.items, form.invoiceDiscount, form.charges), [form]);
  const patch = data => setForm(current => ({ ...current, ...data }));
  const patchItem = (index, data) => patch({ items: form.items.map((item, i) => i === index ? { ...item, ...data } : item) });
  const chooseProduct = (index, productId) => { const product = products.find(item => item.id === productId); if (!product) return patchItem(index, { productId }); patchItem(index, { productId, productName: product.name, description: product.description, unitPrice: product.price, taxType: product.taxCategory, taxRate: product.taxRate, hsnSac: product.hsnSac }); };
  const save = () => { const next = validateQuotation(form, { allowDiscount: discountAuthorized }); setErrors(next); if (!Object.keys(next).length) onSave({ ...form, customer: selectedCustomer, ...totals }); };
  return <main className="quotation-page quotation-form-page"><header className="quotation-header"><div><span className="quote-eyebrow">QUOTATION WORKSPACE</span><h1>{initial?.id ? `Edit ${initial.quoteNumber}` : 'Create Quotation'}</h1><p>{readOnly ? 'This quotation is read-only because of its current status.' : 'Create a customer-ready quotation with instant preview calculations.'}</p></div><div className="quote-header-actions"><button className="quote-btn secondary" onClick={onCancel}>Cancel</button>{!readOnly && <button className="quote-btn primary" onClick={save}>Save Draft</button>}</div></header>
    {!discountAuthorized && <div className="quote-alert warning">You do not have permission to apply this discount. This is a mock permission state.</div>}
    <div className="quote-form-layout"><div className="quote-form-main">
      <section className="quote-card"><h2>Customer information</h2><div className="quote-fields two"><label>Searchable customer<SearchablePicker disabled={readOnly} value={form.customerId} onChange={customerId => patch({ customerId })} items={customers} getLabel={customer => `${customer.name} · ${customer.code}`} getSearchText={customer => `${customer.name} ${customer.code} ${customer.email} ${customer.mobile}`} placeholder="Search name, code, email or mobile" />{errors.customerId && <small className="quote-error">{errors.customerId}</small>}</label></div>{selectedCustomer && <div className="quote-customer-preview"><strong>{selectedCustomer.name} <span>{selectedCustomer.code}</span></strong><span>{selectedCustomer.email} · {selectedCustomer.mobile}</span><span><b>Billing:</b> {selectedCustomer.billingAddress}</span><span><b>Shipping:</b> {selectedCustomer.shippingAddress}</span><span><b>Tax:</b> {selectedCustomer.taxInfo}</span></div>}</section>
      <section className="quote-card"><h2>Quotation details</h2><div className="quote-fields three"><label>Quote number<input value={initial?.quoteNumber || 'QT-2026-000001 (preview)'} readOnly /></label><label>Quotation date<input type="date" disabled={readOnly} value={form.quotationDate} onChange={event => patch({ quotationDate: event.target.value })} />{errors.quotationDate && <small className="quote-error">{errors.quotationDate}</small>}</label><label>Valid until<input type="date" disabled={readOnly} value={form.validUntil} onChange={event => patch({ validUntil: event.target.value })} />{errors.validUntil && <small className="quote-error">{errors.validUntil}</small>}</label><label>Reference<input disabled={readOnly} placeholder="REF-PO-2026-001" value={form.reference} onChange={event => patch({ reference: event.target.value })} /></label></div></section>
      <section className="quote-card"><div className="quote-section-heading"><div><h2>Items</h2><p>Product and service pricing is a frontend preview.</p></div>{!readOnly && <button className="quote-btn secondary small" onClick={() => patch({ items: [...form.items, emptyItem()] })}><Add /> Add item</button>}</div>{errors.items && <p className="quote-error">{errors.items}</p>}<div className="quote-table-wrap"><table className="quote-items-table"><thead><tr><th>Product / Service</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Discount</th><th>Tax</th><th>Total</th><th>Remove</th></tr></thead><tbody>{form.items.map((item, index) => { const calc = lineTotals(item); return <tr key={item.id}><td><SearchablePicker className="quote-product-picker" disabled={readOnly} value={item.productId} onChange={productId => chooseProduct(index, productId)} items={products} getLabel={product => `${product.name} (${product.code})`} getSearchText={product => `${product.name} ${product.code} ${product.description} ${product.hsnSac}`} placeholder="Search product or code" />{errors[`item-${index}`] && <small className="quote-error">{errors[`item-${index}`]}</small>}</td><td><textarea disabled={readOnly} value={item.description} onChange={event => patchItem(index, { description: event.target.value })} /></td><td><input min="0.01" type="number" disabled={readOnly} value={item.quantity} onChange={event => patchItem(index, { quantity: event.target.value })} /></td><td><input min="0" type="number" disabled={readOnly} value={item.unitPrice} onChange={event => patchItem(index, { unitPrice: event.target.value })} /></td><td><select disabled={readOnly} value={item.discountType} onChange={event => patchItem(index, { discountType: event.target.value })}><option value="percentage">%</option><option value="fixed">Fixed</option></select><input min="0" type="number" disabled={readOnly} value={item.discountType === 'percentage' ? item.discountRate : item.discountAmount} onChange={event => patchItem(index, item.discountType === 'percentage' ? { discountRate: event.target.value } : { discountAmount: event.target.value })} /></td><td><select disabled={readOnly} value={item.taxType} onChange={event => patchItem(index, { taxType: event.target.value })}><option>GST</option><option>CGST</option><option>SGST</option><option>IGST</option><option>VAT</option><option>Custom Tax</option></select><input min="0" type="number" disabled={readOnly} value={item.taxRate} onChange={event => patchItem(index, { taxRate: event.target.value })} /><small>HSN/SAC {item.hsnSac || '—'}</small></td><td><strong>{currency(calc.total)}</strong></td><td>{!readOnly && <button className="quote-icon-btn" aria-label="Remove item" onClick={() => patch({ items: form.items.filter((_, i) => i !== index) })}><DeleteOutline /></button>}</td></tr>; })}</tbody></table></div></section>
      <section className="quote-card"><h2>Discount & charges</h2><div className="quote-fields three"><label>Invoice discount type<select disabled={readOnly} value={form.invoiceDiscount.type} onChange={event => patch({ invoiceDiscount: { ...form.invoiceDiscount, type: event.target.value } })}><option value="percentage">Percentage</option><option value="fixed">Fixed Amount</option></select></label><label>Invoice discount {form.invoiceDiscount.type === 'percentage' ? '(maximum 20%)' : 'amount'}<input type="number" min="0" disabled={readOnly} value={form.invoiceDiscount.value} onChange={event => patch({ invoiceDiscount: { ...form.invoiceDiscount, value: event.target.value } })} />{errors.discount && <small className="quote-error">{errors.discount}</small>}</label>{!readOnly && <label className="quote-check"><input type="checkbox" checked={discountAuthorized} onChange={event => setDiscountAuthorized(event.target.checked)} /> Mock discount permission</label>}</div><div className="quote-charges"><h3>Optional charges</h3>{form.charges.map((charge, index) => <div className="quote-charge-row" key={charge.id}><input disabled={readOnly} value={charge.name} placeholder="Shipping / Handling / Convenience / Custom" onChange={event => patch({ charges: form.charges.map((item, i) => i === index ? { ...item, name: event.target.value } : item) })} /><select disabled={readOnly} value={charge.type} onChange={event => patch({ charges: form.charges.map((item, i) => i === index ? { ...item, type: event.target.value } : item) })}><option value="fixed">Fixed</option><option value="percentage">Percentage</option></select><input disabled={readOnly} type="number" min="0" value={charge.amount} onChange={event => patch({ charges: form.charges.map((item, i) => i === index ? { ...item, amount: event.target.value } : item) })} />{!readOnly && <button className="quote-icon-btn" onClick={() => patch({ charges: form.charges.filter((_, i) => i !== index) })}><DeleteOutline /></button>}{errors[`charge-${index}`] && <small className="quote-error">{errors[`charge-${index}`]}</small>}</div>)}{!readOnly && <button className="quote-text-btn" onClick={() => patch({ charges: [...form.charges, { id: `charge-${Date.now()}`, name: 'Shipping', type: 'fixed', amount: 0 }] })}>+ Add charge</button>}</div></section>
      <section className="quote-card quote-summary quote-summary-inline"><h2>Quotation summary</h2><div className="quote-summary-rows">{[['Subtotal', totals.subtotal],['Discount', -totals.discountAmount],['Taxable Amount', totals.taxableAmount],['Tax', totals.taxAmount],['Charges', totals.chargesAmount]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{currency(value)}</strong></div>)}<div className="quote-grand-total"><span>Grand Total</span><strong>{currency(totals.totalAmount)}</strong></div></div></section>
      <section className="quote-card"><h2>Notes & terms</h2><div className="quote-fields two"><label>Notes<textarea disabled={readOnly} value={form.notes} onChange={event => patch({ notes: event.target.value })} /></label><label>Terms & Conditions<textarea disabled={readOnly} value={form.termsAndConditions} onChange={event => patch({ termsAndConditions: event.target.value })} /></label></div></section>
    </div></div></main>;
}
