import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Add, ArrowBack, ArrowForward, CheckCircleOutline, ChevronLeft, ChevronRight, DownloadOutlined, EditOutlined, InfoOutlined, MoreVert, Percent, PublicOutlined, ReceiptLongOutlined, Search, SettingsOutlined, VisibilityOutlined } from '@mui/icons-material';
import { Menu, MenuItem, Dialog, DialogTitle, DialogContent, DialogActions } from '@mui/material';
import { authApi } from 'billing-api-client';
import { getDisplayName } from '../../utils/userDisplay';
import { DashboardHeader } from '../../components/dashboard/DashboardHeader';
import { date, exportTaxes, readTaxes, writeTaxes } from './taxStore';
import './Taxes.css';

const applicability = ['Intra & Inter State', 'Intra State', 'Inter State', 'Union Territory', 'Goods', 'Services', 'Specified Goods'];
const emptyTax = { type: 'GST', code: '', name: '', rate: '', applicable: 'Intra & Inter State', country: 'India', from: new Date().toISOString().slice(0, 10), to: '', description: '', active: true, include: true, draft: false };
const Badge = ({ active }) => <span className={`tx-badge ${active ? 'active' : 'inactive'}`}><i />{active ? 'Active' : 'Inactive'}</span>;
const Field = ({ label, children, hint }) => <label className="tx-field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>;
const Select = ({ value, onChange, options, ...props }) => <select {...props} value={value} onChange={e => onChange(e.target.value)}>{options.map(o => <option key={o} value={o}>{o}</option>)}</select>;
const Toggle = ({ label, hint, checked, onChange }) => <label className="tx-toggle"><span><strong>{label}</strong>{hint && <small>{hint}</small>}</span><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /><span className="tx-switch" /></label>;

export function Taxes() {
  const [data, setData] = useState(readTaxes);
  const [notice, setNotice] = useState('');
  const [search, setSearch] = useState('');
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const parts = pathname.split('/').filter(Boolean);
  const target = parts[1];
  const tax = data.taxes.find(t => t.id === target);
  const save = (next, message) => { try { writeTaxes(next); setData(next); setNotice(message); return true; } catch { setNotice('Could not save: browser storage is unavailable or full. Your changes have not been saved.'); return false; } };
  const actor = () => getDisplayName(authApi.getCurrentUser()) || 'Current user';
  const saveTax = values => {
    const now = new Date().toISOString();
    const editing = Boolean(values.id);
    const original = data.taxes.find(t => t.id === values.id);
    const next = { ...values, id: values.id || crypto.randomUUID(), rate: Number(values.rate), createdBy: original?.createdBy || actor(), createdOn: original?.createdOn || now, updatedBy: actor(), updatedOn: now, audit: [{ action: editing ? 'Configuration updated' : 'Configuration created', actor: actor(), at: now }, ...(original?.audit || [])] };
    if (save({ ...data, taxes: editing ? data.taxes.map(t => t.id === next.id ? next : t) : [...data.taxes, next] }, `Tax ${editing ? 'updated' : 'created'} successfully.`)) navigate(`/taxes/${next.id}`);
  };
  const toggleTax = t => { const now = new Date().toISOString(); save({ ...data, taxes: data.taxes.map(item => item.id === t.id ? { ...item, active: !item.active, updatedBy: actor(), updatedOn: now, audit: [{ action: item.active ? 'Tax deactivated' : 'Tax activated', actor: actor(), at: now }, ...item.audit] } : item) }, `${t.name} ${t.active ? 'deactivated' : 'activated'}.`); };
  const title = target === 'gst' ? 'GST Configuration' : target === 'new' ? 'Create Tax' : parts[2] === 'edit' ? 'Edit Tax' : target ? 'Tax Details' : 'Taxes & GST';
  return <div className="tax-module">
    <DashboardHeader searchQuery={search} onSearch={value => { setSearch(value); if (target) navigate('/taxes'); }} onSignOut={() => { localStorage.removeItem('billing_auth_token'); localStorage.removeItem('billing_auth_user'); navigate('/login'); }} />
    <main className="tx-main">
      <nav className="tx-breadcrumb" aria-label="Breadcrumb"><button onClick={() => navigate('/dashboard')}>Home</button><ChevronRight /><button onClick={() => navigate('/taxes')}>Taxes & GST</button>{target && <><ChevronRight /><span>{title}</span></>}</nav>
      {notice && <div className="tx-notice" role="status"><InfoOutlined /><span>{notice}</span><button aria-label="Dismiss message" onClick={() => setNotice('')}>×</button></div>}
      {!target ? <TaxList taxes={data.taxes} search={search} setSearch={setSearch} navigate={navigate} toggleTax={toggleTax} />
        : target === 'gst' ? <GstSettings key={target} data={data} save={save} navigate={navigate} />
        : target === 'new' || (tax && parts[2] === 'edit') ? <TaxForm key={target} tax={tax} taxes={data.taxes} onSave={saveTax} onCancel={() => navigate(tax ? `/taxes/${tax.id}` : '/taxes')} />
        : tax ? <TaxDetails tax={tax} taxes={data.taxes} navigate={navigate} toggleTax={toggleTax} />
        : <section className="tx-card tx-empty"><h2>Tax configuration not found</h2><button onClick={() => navigate('/taxes')}>Back to Taxes & GST</button></section>}
      <footer className="tx-footnote"><span><InfoOutlined /> Sample workspace · Changes saved in this browser</span><span>Not connected to invoice calculations</span></footer>
    </main>
  </div>;
}
function TaxMenu({ tax, navigate, toggleTax }) {
  const [anchor, setAnchor] = useState(null);
  return <><button className="tx-icon" aria-label={`More actions for ${tax.name}`} onClick={e => setAnchor(e.currentTarget)}><MoreVert /></button><Menu anchorEl={anchor} open={Boolean(anchor)} onClose={() => setAnchor(null)}><MenuItem onClick={() => { exportTaxes([tax]); setAnchor(null); }}>Export configuration</MenuItem><MenuItem onClick={() => { navigate(`/taxes/${tax.id}/edit`); setAnchor(null); }}>Edit configuration</MenuItem><MenuItem onClick={() => { toggleTax(tax); setAnchor(null); }}>{tax.active ? 'Deactivate tax' : 'Activate tax'}</MenuItem></Menu></>;
}
function TaxList({ taxes, search, setSearch, navigate, toggleTax }) {
  const [type, setType] = useState('All Tax Types');
  const [status, setStatus] = useState('All Statuses');
  const [country, setCountry] = useState('All Countries');
  const [page, setPage] = useState(1);
  const [size, setSize] = useState(8);
  const [sort, setSort] = useState(null);
  const rows = taxes.filter(t => `${t.code} ${t.name} ${t.type}`.toLowerCase().includes(search.toLowerCase()) && (type === 'All Tax Types' || t.type === type) && (status === 'All Statuses' || t.active === (status === 'Active')) && (country === 'All Countries' || t.country === country));
  if (sort) rows.sort((a, b) => sort.direction * (sort.key === 'rate' ? a.rate - b.rate : a[sort.key].localeCompare(b[sort.key])));
  const pages = Math.max(1, Math.ceil(rows.length / size));
  const current = Math.min(page, pages);
  const change = setter => value => { setter(value); setPage(1); };
  const metrics = [ ['Total Tax Configurations', taxes.length, ReceiptLongOutlined, 'All configured tax rates'], ['Active Tax Rates', taxes.filter(t => t.active).length, Percent, 'Available for billing'], ['GST Configurations', taxes.filter(t => t.type === 'GST').length, PublicOutlined, 'GST · CGST · SGST · IGST'], ['Other Taxes', taxes.filter(t => t.type !== 'GST').length, ReceiptLongOutlined, 'Cess & custom taxes'] ];
  return <>
    <div className="tx-heading"><div><h1>Taxes & GST</h1><p>Manage tax configurations, GST rates, and tax rules for your business.</p></div><div className="tx-actions"><button onClick={() => navigate('/taxes/gst')}><SettingsOutlined />GST Configuration</button><button className="tx-primary" onClick={() => navigate('/taxes/new')}><Add />Add Tax</button></div></div>
    <section className="tx-kpis" aria-label="Tax configuration summary">{metrics.map(([label, value, Icon, caption]) => <article className="tx-card tx-kpi" key={label}><span className="tx-kpi-icon"><Icon /></span><div><span>{label}</span><strong>{value.toString().padStart(2, '0')}</strong><small>{caption}</small></div></article>)}</section>
    <section className="tx-card tx-list"><div className="tx-section-head"><div><h2>Tax configurations <span className="tx-count">{taxes.length}</span></h2><p>A central place for your business tax rates.</p></div><span className="tx-indicator"><i />India workspace</span></div>
      <div className="tx-filters"><label className="tx-search"><Search /><input aria-label="Search taxes" placeholder="Search by tax name, code or type…" value={search} onChange={e => change(setSearch)(e.target.value)} /></label><Select aria-label="Tax type" value={type} onChange={change(setType)} options={['All Tax Types', 'GST', 'Cess', 'Custom', 'VAT']} /><Select aria-label="Status" value={status} onChange={change(setStatus)} options={['All Statuses', 'Active', 'Inactive']} /><Select aria-label="Country" value={country} onChange={change(setCountry)} options={['All Countries', ...new Set(taxes.map(t => t.country))]} /><button onClick={() => { setSearch(''); setType('All Tax Types'); setStatus('All Statuses'); setCountry('All Countries'); setPage(1); }}>Reset</button><button disabled={!rows.length} onClick={() => exportTaxes(rows)}><DownloadOutlined />Export</button></div>
      <div className="tx-table-wrap"><table><thead><tr>{[['code', 'Tax Code'], ['name', 'Tax Name'], ['type', 'Tax Type'], ['rate', 'Rate (%)'], ['applicable', 'Applicable For'], ['from', 'Effective From']].map(([key, label]) => <th key={key} aria-sort={sort?.key === key ? sort.direction === 1 ? 'ascending' : 'descending' : 'none'}><button onClick={() => setSort({ key, direction: sort?.key === key ? -sort.direction : 1 })}>{label}<span>{sort?.key === key ? sort.direction === 1 ? '↑' : '↓' : '↕'}</span></button></th>)}<th>Status</th><th className="tx-right">Actions</th></tr></thead><tbody>{rows.slice((current - 1) * size, current * size).map(t => <tr key={t.id}><td><button className="tx-code" onClick={() => navigate(`/taxes/${t.id}`)}>{t.code}</button></td><td><strong>{t.name}</strong></td><td><span className={`tx-type ${t.type.toLowerCase()}`}>{t.type}</span></td><td className="tx-numeric">{Number(t.rate).toFixed(2)}</td><td>{t.applicable}</td><td>{date(t.from)}</td><td><Badge active={t.active} /></td><td><div className="tx-row-actions"><button className="tx-icon" aria-label={`View ${t.name}`} onClick={() => navigate(`/taxes/${t.id}`)}><VisibilityOutlined /></button><button className="tx-icon" aria-label={`Edit ${t.name}`} onClick={() => navigate(`/taxes/${t.id}/edit`)}><EditOutlined /></button><TaxMenu tax={t} navigate={navigate} toggleTax={toggleTax} /></div></td></tr>)}</tbody></table>{!rows.length && <div className="tx-empty"><Search /><h3>No matching tax configurations</h3><p>Try a different search or reset your filters.</p></div>}</div>
      <div className="tx-pagination"><span>Showing <strong>{rows.length ? (current - 1) * size + 1 : 0}–{Math.min(current * size, rows.length)}</strong> of <strong>{rows.length}</strong> configurations</span><div><label>Rows per page <Select value={size} onChange={value => { setSize(Number(value)); setPage(1); }} options={[8, 16, 32]} /></label><button aria-label="Previous page" disabled={current === 1} onClick={() => setPage(current - 1)}><ChevronLeft /></button>{Array.from({ length: pages }, (_, i) => i + 1).filter(p => p === 1 || p === pages || Math.abs(p - current) < 2).map(p => <button key={p} className={p === current ? 'tx-primary' : ''} aria-current={p === current ? 'page' : undefined} onClick={() => setPage(p)}>{p}</button>)}<button aria-label="Next page" disabled={current === pages} onClick={() => setPage(current + 1)}><ChevronRight /></button></div></div>
    </section><div className="tx-config-promo"><span className="tx-kpi-icon"><SettingsOutlined /></span><div><h3>Make every invoice consistent</h3><p>Manage GST components, rounding preferences, and place of supply rules.</p></div><button onClick={() => navigate('/taxes/gst')}>Manage GST settings <ArrowForward /></button></div>
  </>;
}
function TaxForm({ tax, taxes, onSave, onCancel }) {
  const [form, setForm] = useState(tax || emptyTax);
  const [error, setError] = useState('');
  const update = key => value => setForm(f => ({ ...f, [key]: value }));
  const submit = e => { e.preventDefault(); const code = form.code.trim().toUpperCase(); if (!form.name.trim() || !code) return setError('Enter a tax code and name.'); if (taxes.some(t => t.id !== tax?.id && t.code.toUpperCase() === code)) return setError('This tax code already exists. Use a unique code.'); if (form.to && form.to < form.from) return setError('Effective To must be on or after Effective From.'); setError(''); onSave({ ...form, code, name: form.name.trim() }); };
  return <><div className="tx-heading"><div><h1>{tax ? 'Edit Tax' : 'Create Tax'}</h1><p>{tax ? 'Update tax configuration and billing preferences.' : 'Add a new tax configuration to your billing workspace.'}</p></div><button onClick={onCancel}><ArrowBack />Back</button></div><form onSubmit={submit} className="tx-form-layout"><section className="tx-card"><div className="tx-section-head"><div><h2>Tax information</h2><p>Define the rate and where this tax applies.</p></div><span className="tx-muted">* Required fields</span></div><div className="tx-form-grid">
    <Field label="Tax Type *"><Select value={form.type} onChange={update('type')} options={['GST', 'Cess', 'Custom', 'VAT']} /></Field><Field label="Tax Code *" hint="Unique identifier used in billing and reports."><input required maxLength={30} pattern="[A-Za-z0-9_-]+" title="Use letters, numbers, underscores or hyphens" value={form.code} onChange={e => update('code')(e.target.value)} placeholder="e.g. CGST9" /></Field>
    <Field label="Tax Name *"><input required maxLength={100} value={form.name} onChange={e => update('name')(e.target.value)} placeholder="e.g. Central GST 9%" /></Field><Field label="Tax Rate (%) *"><input required type="number" min="0" max="100" step="0.01" value={form.rate} onChange={e => update('rate')(e.target.value)} placeholder="0.00" /></Field>
    <Field label="Applicable For *"><Select value={form.applicable} onChange={update('applicable')} options={applicability} /></Field><Field label="Country *"><Select value={form.country} onChange={update('country')} options={['India', 'United Arab Emirates', 'Singapore']} /></Field>
    <Field label="Effective From *"><input required type="date" value={form.from} onChange={e => update('from')(e.target.value)} /></Field><Field label="Effective To" hint="Leave blank for an ongoing configuration."><input type="date" min={form.from} value={form.to} onChange={e => update('to')(e.target.value)} /></Field>
    <div className="tx-full"><Field label="Description"><textarea rows={3} maxLength={1000} value={form.description} onChange={e => update('description')(e.target.value)} placeholder="Describe the purpose and applicability of this tax…" /></Field></div>
    </div><div className="tx-options"><h3>Billing preferences</h3><Toggle label="Is Active" hint="Make this tax available for selection." checked={form.active} onChange={update('active')} /><Toggle label="Include in Invoice" hint="Display the tax breakdown on invoices." checked={form.include} onChange={update('include')} /><Toggle label="Allow Edit in Draft" hint="Allow the rate to be adjusted on draft invoices." checked={form.draft} onChange={update('draft')} /></div>{error && <p className="tx-error" role="alert">{error}</p>}<div className="tx-form-footer"><button type="button" onClick={onCancel}>Cancel</button><button className="tx-primary" type="submit"><CheckCircleOutline />Save Tax</button></div></section><aside><section className="tx-card tx-preview"><span className="tx-eyebrow">CONFIGURATION PREVIEW</span><span className="tx-preview-icon"><Percent /></span><h2>{form.name || 'Your tax name'}</h2><p>{form.code || 'TAX CODE'} · {form.type}</p><strong className="tx-big-rate">{Number(form.rate || 0).toFixed(2)}<small>%</small></strong><Badge active={form.active} /><hr /><dl><dt>Applicable for</dt><dd>{form.applicable}</dd><dt>Country</dt><dd>{form.country}</dd><dt>Effective from</dt><dd>{date(form.from)}</dd></dl></section><div className="tx-tip"><InfoOutlined /><p>Use a distinct code for each tax component to keep configurations easy to identify.</p></div></aside></form></>;
}
function TaxDetails({ tax, taxes, navigate, toggleTax }) {
  const [tab, setTab] = useState('Overview');
  const related = taxes.filter(t => t.id !== tax.id && t.type === tax.type);
  const fields = [['Tax Code', tax.code], ['Tax Name', tax.name], ['Tax Type', tax.type], ['Rate', `${Number(tax.rate).toFixed(2)}%`], ['Applicable For', tax.applicable], ['Country', tax.country], ['Effective From', date(tax.from)], ['Effective To', date(tax.to)], ['Description', tax.description || 'No description provided'], ['Created By', tax.createdBy], ['Created On', date(tax.createdOn, true)], ['Last Updated By', tax.updatedBy], ['Last Updated On', date(tax.updatedOn, true)], ['Status', <Badge active={tax.active} />]];
  return <><div className="tx-heading"><div><h1>Tax Details</h1><p>View configuration, usage, and the history of this tax.</p></div><div className="tx-actions"><button onClick={() => navigate(`/taxes/${tax.id}/edit`)}><EditOutlined />Edit Tax</button><TaxMenu tax={tax} navigate={navigate} toggleTax={toggleTax} /></div></div><section className="tx-card"><div className="tx-detail-hero"><span className="tx-preview-icon"><Percent /></span><div><div className="tx-actions"><h2>{tax.name}</h2><Badge active={tax.active} /></div><p>{tax.code} <span> / </span> {tax.type} <span> / </span> {tax.country}</p></div><strong>{Number(tax.rate).toFixed(2)}<small>%</small></strong></div><div className="tx-tabs" role="tablist">{['Overview', 'Usage', 'Audit Trail', 'Related Taxes'].map(t => <button role="tab" aria-selected={tab === t} key={t} onClick={() => setTab(t)}>{t}</button>)}</div><div className="tx-tab-content" role="tabpanel" aria-label={tab}>
    {tab === 'Overview' && <><h3>Configuration details</h3><dl className="tx-details">{fields.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><h3>Invoice preferences</h3><div className="tx-preferences">{[['Include in Invoice', tax.include], ['Allow Edit in Draft', tax.draft]].map(([key, value]) => <span key={key}>{key}<strong>{value ? 'Enabled' : 'Disabled'}</strong></span>)}</div></>}
    {tab === 'Usage' && <><h3>Tax usage</h3><p className="tx-muted">Invoice associations will appear here when the tax service is connected.</p><div className="tx-empty"><ReceiptLongOutlined /><h3>No linked invoice data</h3><p>This browser workspace does not track live invoices or taxable totals.</p><button onClick={() => navigate('/invoices')}>Open invoices <ArrowForward /></button></div></>}
    {tab === 'Audit Trail' && <><h3>Configuration history</h3><p className="tx-muted">Local workspace activity · newest first</p><ol className="tx-timeline">{tax.audit.map((event, index) => <li key={`${event.at}-${index}`}><span className="tx-timeline-dot" /><div><strong>{event.action}</strong><p>{event.actor}</p></div><time>{date(event.at, true)}</time></li>)}</ol></>}
    {tab === 'Related Taxes' && <><h3>Other {tax.type} configurations</h3><p className="tx-muted">Grouped by tax type. These are not automatically combined on invoices.</p><div className="tx-related">{related.map(t => <button key={t.id} onClick={() => { navigate(`/taxes/${t.id}`); setTab('Overview'); }}><span className="tx-kpi-icon"><Percent /></span><span><strong>{t.name}</strong><small>{t.code} · {t.applicable}</small></span><Badge active={t.active} /><ChevronRight /></button>)}</div>{!related.length && <p>No related configurations.</p>}</>}
    </div></section></>;
}
function GstSettings({ data, save, navigate }) {
  const [tab, setTab] = useState('GST Rates');
  const [settings, setSettings] = useState(data.settings);
  const [rates, setRates] = useState(data.rates);
  const [editing, setEditing] = useState(null);
  const [error, setError] = useState('');
  const [dirty, setDirty] = useState(false);
  const update = key => value => { setSettings(s => ({ ...s, [key]: value })); setDirty(true); };
  const submit = e => { e.preventDefault(); if (settings.gstin && !/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(settings.gstin)) { setTab('General'); setError('Enter a valid 15-character GSTIN or leave it blank.'); return; } setError(''); if (save({ ...data, settings, rates }, 'GST settings saved in this browser.')) setDirty(false); };
  const saveRate = e => { e.preventDefault(); if (rates.some(r => r.id !== editing.id && r.component === editing.component && r.transaction === editing.transaction && Number(r.rate) === Number(editing.rate))) { setError('This transaction, component and rate combination already exists.'); return; } setRates(rows => editing.id ? rows.map(r => r.id === editing.id ? { ...editing, rate: Number(editing.rate) } : r) : [...rows, { ...editing, id: crypto.randomUUID(), rate: Number(editing.rate) }]); setEditing(null); setError(''); setDirty(true); };
  return <><form onSubmit={submit}><div className="tx-heading"><div><h1>GST Configuration</h1><p>Configure GST settings and tax rules for your India workspace.</p></div><div className="tx-actions">{dirty && <span className="tx-unsaved">Unsaved changes</span>}<button type="button" onClick={() => { if (!dirty || window.confirm('Discard unsaved GST changes?')) navigate('/taxes'); }}>Back to taxes</button><button className="tx-primary" type="submit"><CheckCircleOutline />Save Changes</button></div></div><section className="tx-card"><div className="tx-tabs" role="tablist">{['General', 'GST Rates', 'Rounding & Rules', 'Place of Supply'].map(t => <button type="button" role="tab" aria-selected={tab === t} key={t} onClick={() => setTab(t)}>{t}</button>)}</div><div className="tx-tab-content" role="tabpanel" aria-label={tab}>{error && !editing && <p className="tx-error" role="alert">{error}</p>}
    {tab === 'GST Rates' && <><div className="tx-info"><InfoOutlined /><span>Configure components for intra-state, inter-state, and union territory transactions. These are illustrative rates, not a current statutory rate schedule.</span></div><div className="tx-section-head tx-no-pad"><div><h2>GST component rates</h2><p>Manage the component rates available in this workspace.</p></div><span className="tx-count">{rates.length} rates</span></div><div className="tx-table-wrap"><table><thead><tr><th>Transaction Type</th><th>Tax Component</th><th>Rate (%)</th><th>Status</th><th className="tx-right">Action</th></tr></thead><tbody>{rates.map(r => <tr key={r.id}><td>{r.transaction}</td><td><span className="tx-type gst">{r.component}</span></td><td className="tx-numeric">{Number(r.rate).toFixed(2)}</td><td><Badge active={r.active} /></td><td className="tx-right"><button type="button" className="tx-icon" aria-label={`Edit ${r.component} rate`} onClick={() => { setEditing({ ...r }); setError(''); }}><EditOutlined /></button></td></tr>)}</tbody></table></div><button type="button" className="tx-primary tx-add-rate" onClick={() => { setEditing({ transaction: 'Intra State', component: 'CGST', rate: '', active: true }); setError(''); }}><Add />Add GST Rate</button></>}
    {tab === 'General' && <><h2>GST General Settings</h2><p className="tx-muted">Business registration and default GST preferences.</p><Toggle label="Enable GST" hint="Store GST preferences for your billing workspace." checked={settings.enabled} onChange={update('enabled')} /><div className="tx-form-grid tx-no-pad"><Field label="Business legal name"><input value={settings.legalName} onChange={e => update('legalName')(e.target.value)} placeholder="Enter registered business name" /></Field><Field label="GSTIN" hint="15-character Goods and Services Tax Identification Number."><input maxLength={15} value={settings.gstin} onChange={e => update('gstin')(e.target.value.toUpperCase())} placeholder="Enter your GSTIN" /></Field><Field label="Registered state / territory"><Select value={settings.state} onChange={update('state')} options={['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']} /></Field><Field label="Registration scheme"><Select value={settings.scheme} onChange={update('scheme')} options={['Regular', 'Composition', 'Unregistered']} /></Field></div></>}
    {tab === 'Rounding & Rules' && <><h2>Rounding Rules</h2><p className="tx-muted">Define calculation precision and invoice rounding preferences.</p><div className="tx-form-grid tx-no-pad"><Field label="Rounding method"><Select value={settings.rounding} onChange={update('rounding')} options={['Nearest rupee', 'Round up', 'Round down', 'No rounding']} /></Field><Field label="Decimal precision"><Select value={settings.precision} onChange={update('precision')} options={['2', '3', '4']} /></Field><Field label="Tax calculation level"><Select value={settings.calculation} onChange={update('calculation')} options={['Per line item', 'Invoice total']} /></Field></div><Toggle label="Prices include tax" hint="Treat entered item prices as tax-inclusive." checked={settings.inclusive} onChange={update('inclusive')} /><Toggle label="Apply tax to shipping charges" checked={settings.shipping} onChange={update('shipping')} /><div className="tx-info"><InfoOutlined /><span>Rounding preview: ₹1,245.56 → <strong>₹{({ 'Nearest rupee': '1,246.00', 'Round up': '1,246.00', 'Round down': '1,245.00', 'No rounding': '1,245.56' })[settings.rounding]}</strong></span></div></>}
    {tab === 'Place of Supply' && <><h2>Place of Supply Rules</h2><p className="tx-muted">Set how the transaction location is captured.</p><div className="tx-form-grid tx-no-pad"><Field label="Default place of supply source"><Select value={settings.supply} onChange={update('supply')} options={['Customer billing address', 'Customer shipping address', 'Select manually']} /></Field><Field label="When place of supply is missing"><Select value={settings.missing} onChange={update('missing')} options={['Require place of supply', 'Use registered business state']} /></Field></div><Toggle label="Allow manual override in drafts" hint="Let users change the place of supply before an invoice is issued." checked={settings.reverse} onChange={update('reverse')} /><div className="tx-rule-cards"><article><span className="tx-type gst">Intra State</span><h3>Same state</h3><p>Supplier and place of supply match.</p><strong>CGST + SGST</strong></article><article><span className="tx-type gst">Inter State</span><h3>Different states</h3><p>Supplier and place of supply differ.</p><strong>IGST</strong></article></div><div className="tx-info"><InfoOutlined /><span>These preferences are stored locally. Transaction-specific exceptions require backend tax-rule integration.</span></div></>}
    </div></section></form><Dialog open={Boolean(editing)} onClose={() => { setEditing(null); setError(''); }} fullWidth maxWidth="sm" PaperProps={{ className: 'tx-dialog' }} aria-labelledby="tx-rate-title">{editing && <form onSubmit={saveRate}><DialogTitle id="tx-rate-title">{editing.id ? 'Edit GST Rate' : 'Add GST Rate'}</DialogTitle><DialogContent><p className="tx-muted">Define a component rate for a transaction type.</p><div className="tx-form-grid tx-no-pad"><Field label="Transaction Type *"><Select value={editing.transaction} onChange={value => setEditing({ ...editing, transaction: value, component: value === 'Inter State' ? 'IGST' : value === 'UT (Union Territory)' ? 'UGST' : 'CGST' })} options={['Intra State', 'Inter State', 'UT (Union Territory)']} /></Field><Field label="Tax Component *"><Select value={editing.component} onChange={value => setEditing({ ...editing, component: value })} options={editing.transaction === 'Intra State' ? ['CGST', 'SGST'] : editing.transaction === 'Inter State' ? ['IGST'] : ['UGST']} /></Field><Field label="Rate (%) *"><input autoFocus required type="number" min="0" max="100" step="0.01" value={editing.rate} onChange={e => setEditing({ ...editing, rate: e.target.value })} /></Field></div><Toggle label="Is Active" checked={editing.active} onChange={value => setEditing({ ...editing, active: value })} />{error && <p className="tx-error" role="alert">{error}</p>}<p className="tx-muted">Apply the rate, then select Save Changes to persist GST settings.</p></DialogContent><DialogActions><button type="button" onClick={() => { setEditing(null); setError(''); }}>Cancel</button><button type="submit" className="tx-primary">Apply Rate</button></DialogActions></form>}</Dialog></>;
}
