import { useEffect, useState } from 'react';
import { Alert, Snackbar } from '@mui/material';
import { mockCustomers, mockProducts, mockQuotations } from './data/quotationMockData';
import { quotationTotals } from './utils/quotationCalculations';
import { QuotationList } from './pages/QuotationList';
import { QuotationForm, newQuotation } from './components/QuotationForm';
import { QuotationDetails } from './pages/QuotationDetails';
import { QuotationDialog } from './components/QuotationDialogs';
import './styles/quotations.css';
const storageKey = 'ibms_quotation_demo_data';
const hydrate = quote => ({ ...quote, ...quotationTotals(quote.items, quote.invoiceDiscount, quote.charges) });
// TODO: Replace these local mock operations with /api/v1/quotations during integration.
export const quotationMockRepository = { getQuotations: quotes => quotes, getQuotationById: (quotes,id) => quotes.find(q=>q.id===id), createQuotation: (quotes,quote) => [...quotes,quote], updateQuotation: (quotes,quote) => quotes.map(q=>q.id===quote.id?quote:q), sendQuotation: (quotes,id) => quotes.map(q=>q.id===id?{...q,status:'Sent'}:q), approveQuotation: (quotes,id) => quotes.map(q=>q.id===id?{...q,status:'Approved'}:q), cancelQuotation: (quotes,id,reason) => quotes.map(q=>q.id===id?{...q,status:'Cancelled',cancellationReason:reason}:q), convertQuotation: (quotes,id,invoice) => quotes.map(q=>q.id===id?{...q,status:'Converted',convertedInvoiceId:invoice}:q) };
export function QuotationManagement() { const [quotes,setQuotes]=useState(()=>{try{return JSON.parse(localStorage.getItem(storageKey))?.map(hydrate)||mockQuotations.map(hydrate)}catch{return mockQuotations.map(hydrate)}}); const [screen,setScreen]=useState('list'); const [current,setCurrent]=useState(null); const [dialog,setDialog]=useState(null); const [notice,setNotice]=useState('');
 useEffect(()=>localStorage.setItem(storageKey,JSON.stringify(quotes)),[quotes]); const open=(mode,quote=null)=>{setCurrent(quote);setScreen(mode)}; const persist=(quote,isNew=false)=>{const finished=hydrate({...quote,id:quote.id||`q-${Date.now()}`,quoteNumber:quote.quoteNumber||`QT-2026-${String(quotes.length+1).padStart(6,'0')}`,status:quote.status||'Draft',communications:quote.communications||[],auditLogs:[...(quote.auditLogs||[]),{date:new Date().toISOString().slice(0,10),action:isNew?'Created':'Edited',user:'Admin',description:isNew?'Quotation saved as draft.':'Draft updated.'}],convertedInvoiceId:quote.convertedInvoiceId||null});setQuotes(all=>isNew?quotationMockRepository.createQuotation(all,finished):quotationMockRepository.updateQuotation(all,finished));setNotice(isNew?'Quotation saved as draft.':'Quotation draft updated.');setScreen('details');setCurrent(finished)};
 const transition=(type,reason)=>{const quote=current; if(type==='approve'&&!reason){setDialog(null);setNotice('You do not have permission to approve this quotation.');return;} if(type==='send'&&quote.validUntil<new Date().toISOString().slice(0,10)){setDialog(null);setNotice('This quotation has expired and cannot be sent.');return;} if(type==='convert'&&quote.status==='Converted'){setDialog(null);setNotice('This quotation has already been converted to an invoice.');return;} const action={send:'Sent',approve:'Approved',cancel:'Cancelled',convert:'Converted'}[type]; const invoice=type==='convert'?`INV-2026-${String(quotes.length+1).padStart(6,'0')}`:null; const message={send:'Quotation sent successfully.',approve:'Quotation approved successfully.',cancel:'Quotation cancelled.',convert:'Invoice created successfully.'}[type]; const updated=hydrate({...quote,status:action,convertedInvoiceId:invoice||quote.convertedInvoiceId,cancellationReason:reason||quote.cancellationReason,cancelledBy:type==='cancel'?'Admin':quote.cancelledBy,cancelledAt:type==='cancel'?new Date().toISOString():quote.cancelledAt,communications:type==='send'?[...(quote.communications||[]),{date:new Date().toISOString().slice(0,10),type:'Email',recipient:quote.customer.email,subject:`Quotation ${quote.quoteNumber}`,status:'Sent',sentBy:'Admin',message:'Your quotation is ready for review.'}]:quote.communications,auditLogs:[...(quote.auditLogs||[]),{date:new Date().toISOString().slice(0,10),action:type==='send'?'Sent':type==='approve'?'Approved':type==='cancel'?'Cancelled':'Converted to Invoice',user:'Admin',description:type==='cancel'?`Cancelled: ${reason||'No reason provided'}`:type==='convert'?`Converted to ${invoice}`:`${action} by Admin`} ]}); setQuotes(all=>quotationMockRepository.updateQuotation(all,updated));setCurrent(updated);setDialog(null);setNotice(message);};
 if(screen==='create'||screen==='edit')return <QuotationForm initial={screen==='edit'?current:newQuotation()} customers={mockCustomers} products={mockProducts} onSave={quote=>persist(quote,screen==='create')} onCancel={()=>setScreen(current?'details':'list')} />;
 if(screen==='details'&&current)return <><QuotationDetails quotation={current} onBack={()=>setScreen('list')} onEdit={quote=>open('edit',quote)} onAction={(type,quote)=>{setCurrent(quote);setDialog(type)}}/><QuotationDialog type={dialog} quotation={current} onClose={()=>setDialog(null)} onConfirm={transition}/><Snackbar open={!!notice} autoHideDuration={4000} onClose={()=>setNotice('')}><Alert severity="success" variant="filled">{notice}</Alert></Snackbar></>;
 return <><QuotationList quotations={quotes} customers={mockCustomers} onCreate={()=>open('create')} onView={quote=>open('details',quote)} onEdit={quote=>open('edit',quote)} onAction={(type,quote)=>{setCurrent(quote);setDialog(type)}}/><QuotationDialog type={dialog} quotation={current} onClose={()=>setDialog(null)} onConfirm={transition}/><Snackbar open={!!notice} autoHideDuration={4000} onClose={()=>setNotice('')}><Alert severity="success" variant="filled">{notice}</Alert></Snackbar></>;
}
